version: "3.8"
services:
  nodejs-server:
    build:
      context: ./api
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    image: Nextjs-image:tag
    container_name: node-api
    volumes:
      - ./api:/usr/src/app/api
      - /usr/src/app/api/node_modules
  nextjs-ui:
    build:
      context: ./my-app
    ports:
      - "3000:3000"
    image: Nextjs-ui-image2
    container_name: nextjs-ui:tag
    stdin_open: true
    volumes:
      - ./my-app:/usr/src/app/my-app
      - /usr/src/app/my-app/node_modules
