version: "3.1"
services:
  nextjs:
    ports:
      - 3000:3000
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - port=3000
    volumes:
      - ./:./nextjs:ro
      - ./my-app/node-modules
