version: "3.8"
services:
  # nodejs-server:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3001"
  #   container_name: node-api
  #   volumes:
  #     - ./api:/usr/src/app/pages/api
  #     - /usr/src/app/api/node_modules
  nextjs-ui:
    build:
      context: .
    ports:
      - "3000:3000"
    container_name: nextjs-ui
    stdin_open: true
    volumes:
      - ./my-app:/usr/src/app/my-app
      - /usr/src/app/my-app/node_modules
